#ifndef READ_RECEIPT_NATIVE_FS_H
#define READ_RECEIPT_NATIVE_FS_H

enum ReadReceiptFsResult {
    READ_RECEIPT_FS_OK = 0,
    READ_RECEIPT_FS_EXISTS = 1,
    READ_RECEIPT_FS_UNAVAILABLE = 2,
    READ_RECEIPT_FS_INVALID_ARGUMENT = 3,
    READ_RECEIPT_FS_NOT_FOUND = 4,
    READ_RECEIPT_FS_IDENTITY_MISMATCH = 5,
    READ_RECEIPT_FS_UNSUPPORTED = 6,
    READ_RECEIPT_FS_IO_ERROR = 7,
};

#endif
